[package]
name = "TranslateOnTime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.0"
tesseract-sys = "0.6.1"
hotwatch = "0.5"
